services:
  postgres:
    image: postgres:17.5
    restart: always
    container_name: auth-workshop
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_workshop
      POSTGRES_HOST_AUTH_METHOD: trust
